const imgLinks =  [
    {
      img:'./assets/img/images/AnimeBlog.jpg',
      github:'https://github.com/Mod8124/blogAnime-node.git',
      url:'https://blog-anime-node.herokuapp.com'
    },
    {
      img:'./assets/img/images/rock.jpg',
      github:'https://github.com/Mod8124/Classic-Rock-paper-scissors.git',
      url:'https://classic-rock-paper-scissors.vercel.app'
    },
    {
      img:'./assets/img/images/clone-netflix.jpg',
      github:'https://github.com/Mod8124/Netflix-clone-with-next-js.git',
      url:'https://netflix-clone-mod8124.vercel.app'
    },
    {
      img:'./assets/img/images/ecommerce.jpg',
      github:'https://github.com/Mod8124/ecommerce-vue.git',
      url:'https://ecommerce-vue-seven.vercel.app'
    },
    
    {
      img:'./assets/img/images/jhonny.jpg',
      github:'https://github.com/Mod8124/jhonny_webSite.git',
      url:'https://mod8124.github.io/jhonny_webSite'
    },
    {
      img:'./assets/img/images/rest-country.jpg',
      github:'https://github.com/Mod8124/rest-countries-vue.git',
      url:'https://rest-countries-mv56ciqhj-mod8124.vercel.app'
    },
    {
      img:'./assets/img/images/sunnyside.jpg',
      github:'https://github.com/Mod8124/sunnyside.git',
      url:'https://mod8124.github.io/sunnyside'
    },
    {
      img:'./assets/img/images/bank.jpg',
      github:'https://github.com/Mod8124/Easybank.git',
      url:'https://mod8124.github.io/Easybank'
    },
  
    {
      img:'./assets/img/images/comment.jpg',
      github:'https://github.com/Mod8124/interartive-comments.git',
      url:'https://interartive-comments.vercel.app'
    },
    {
      img:'./assets/img/images/ajedrez.jpg',
      github:'https://github.com/Mod8124/ChessWebsite.git',
      url:'https://chess-website.vercel.app'
    },
    {
      img:'./assets/img/images/food.jpg',
      github:'https://github.com/Mod8124/Food_webSite.git',
      url:'https://food-web-site.vercel.app'
    },
    {
      img:'./assets/img/images/web-dakMode.jpg',
      github:'https://github.com/Mod8124/landing-page-dark.git',
      url:'https://mod8124.github.io/landing-page-dark'
    },
]

export default imgLinks;